### ISSUE TITLE
enocean mqtt not starting

### ISSUE THREAD

**Issue by UsefulVid** [mak-gitdev/HA_enoceanmqtt#135]
### The problem

I can try to start enoceanmqtt addon but it fails. See logs

### What type of installation are you running?

Addon

### What version of HA_enoceanmqtt has the issue?

0.1.28-2 

### What type of Home Assitant installation are you running?

Home Assistant OS

### Anything in the logs that might be useful to solve the issue? (Strongly recommended if applicable)

```txt
2024-03-13 14:13:04.187 ERROR (MainThread) [homeassistant.components.hassio.handler] /addons/ec247e54_ha_enoceanmqtt_dev/stats return code 400
2024-03-13 14:13:04.187 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/ec247e54_ha_enoceanmqtt_dev/stats -


s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Preparing to start...
Retrieved devices file: /config/enoceanmqtt.devices
Overwrite use_dev_name_in_entity to FALSE
Starting EnOceanMQTT...
/usr/lib/python3.11/html/parser.py:170: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  k = self.parse_starttag(i)
2024-03-13 14:17:14,298 INFO: Logging to file: /config/enoceanmqtt.log
2024-03-13 14:17:14,299 INFO: Loading config file /data/enoceanmqtt.conf
Traceback (most recent call last):
  File "/app/venv/bin/enoceanmqtt", line 33, in <module>
    sys.exit(load_entry_point('enocean-mqtt', 'console_scripts', 'enoceanmqtt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/enocean-mqtt/enoceanmqtt/enoceanmqtt.py", line 110, in main
    sensors, global_config = load_config_file(conf['config'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/enocean-mqtt/enoceanmqtt/enoceanmqtt.py", line 65, in load_config_file
    new_sens[key] = int(config_parser[section][key], 0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 0: 'eltako/FSB61NP'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by UsefulVid** [comment]
can be closed :) wrong symbol in name
